language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t asywe16/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true asywe16/docker-react npm run test
